<$PLAN9/src/mkhdr

LIBFILES=\
	error\
	file\
	fs\
	pack\

SHORTLIB=venti sec thread mux bio 9
LIB=${LIBFILES:%=%.$O}

HFILES=\
	$PLAN9/include/venti.h\
	stdinc.h\
	error.h\
	vac.h\
	dat.h\
	fns.h\

TARG=vac vtdump

CFILES=${TARG:%=%.c} ${LIBFILES:%=%.c} srcload.c vactest.c

UPDATE=\
	mkfile\
	$CFILES\
	$HFILES\
	${TARG:%=/386/bin/%}

default:V: all

test:V: $O.srcload $O.wtest $O.rtest $O.vtdump $O.vtread

<$PLAN9/src/mkmany
