<$PLAN9/src/mkhdr

LIBFILES=\
	error\
	file\
	pack\
	glob\

LIB=${LIBFILES:%=%.$O} $PLAN9/lib/libventi.a

HFILES=\
	$PLAN9/include/venti.h\
	stdinc.h\
	error.h\
	vac.h\
	dat.h\
	fns.h\

TARG=vac vacfs unvac

default:V: all

<$PLAN9/src/mkmany

testglob:V: $O.testinc
	$O.testinc exc <exc.in >exc.test
	diff exc.out exc.test
	ls -l exc.out exc.test


