<$PLAN9/src/mkhdr

TARG=grap
OFILES=\
	grap.$O\
	grapl.$O\
	main.$O\
	input.$O\
	print.$O\
	frame.$O\
	for.$O\
	coord.$O\
	ticks.$O\
	plot.$O\
	label.$O\
	misc.$O\

HFILES=grap.h\
	y.tab.h\

YFILES=grap.y
LFILES=grapl.lx

<$PLAN9/src/mkone
YFLAGS=-d -S

grap.c:	y.tab.c
	mv $prereq $target

grapl.c:D: $LFILES
	$LEX -t $prereq > $target

clean:V:
	rm -f [$OS].out *.[$OS] y.tab.? lex.yy.c grapl.c grap.c grap
