<$PLAN9/src/mkhdr

LIB=libsec.a
SFILES=\
	md5block.s\
	sha1block.s\

HFILES=$PLAN9/include/libsec.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$PLAN9/src/mksyslib

%.s: %.spp
	if [ `uname` = OpenBSD ] || [ `uname` = Darwin ]
	then
		gcc -xc -D__`uname`__ -E $stem.spp >$stem.s
	else
		cpp $stem.spp >$stem.s
	fi

CLEANFILES=md5block.s sha1block.s
