PLAN9=../../..
<$PLAN9/src/mkhdr

LIBOFILES=\
	arena.$O\
	arenas.$O\
	buildbuck.$O\
	clump.$O\
	config.$O\
	conv.$O\
	dcache.$O\
	dump.$O\
	httpd.$O\
	icache.$O\
	ifile.$O\
	index.$O\
	lump.$O\
	lumpcache.$O\
	lumpqueue.$O\
	part.$O\
	score.$O\
	sortientry.$O\
	stats.$O\
	syncarena.$O\
	syncindex0.$O\
	unwhack.$O\
	utils.$O\
	unittoull.$O\
	whack.$O\
	xml.$O\
	zeropart.$O\

SLIB=libvs.a

LIB=$SLIB
SHORTLIB=venti httpd bin sec thread 9

HFILES=	dat.h\
	fns.h\
	stdinc.h\

TARG=\
	venti\
	fmtarenas\
	fmtisect\
	fmtindex\
	buildindex\
	checkarenas\
	checkindex\
	clumpstats\
	findscore\
	rdarena\
	wrarena\
	syncindex\
	verifyarena\
	sync\
	read\
	write\
	copy\
	wb\

BIN=$BIN/venti

it:V: all

<$PLAN9/src/mkmany

$SLIB: $LIBOFILES
	$AR rvc $SLIB $LIBOFILES

# xml.c:D:	mkxml dat.h
# 	./mkxml dat.h > xml.c

ainstall:V: ${TARG:%=%.ainstall}

%.ainstall:V:	$O.%
	scp $prereq amsterdam:/usr/local/bin/venti/$stem

