<$PLAN9/src/mkhdr

TARG=addhash bayes msgtok
HFILES=
OFILES=
LIB=

BIN=$BIN/upas
<$PLAN9/src/mkmany

# msg tokenizer
$O.regen: regcomp.$O dfa.$O
dfa.$O regcomp.$O regen.$O: dfa.h

$PLAN9/mail/lib/classify.re: $O.regen
	if(~ $cputype $objtype)
		$O.regen >x && cp x $target

$O.msgtok: dfa.$O

# msg database 
msgdbx.$O msgdb.$O: msgdb.h

# hash table creator/dumper
$O.msgdb: msgdbx.$O

$O.msgclass: hash.$O msgdbx.$O

$O.addhash: hash.$O 

$O.bayes: hash.$O


