<$PLAN9/src/mkhdr

LIB=libbio.a

OFILES=\
	bbuffered.$O\
	bfildes.$O\
	bflush.$O\
	bfmt.$O\
	bgetc.$O\
	bgetd.$O\
	binit.$O\
	boffset.$O\
	bprint.$O\
	bputc.$O\
	brdline.$O\
	brdstr.$O\
	bread.$O\
	bseek.$O\
	bwrite.$O\
	bgetrune.$O\
	bputrune.$O\

HFILES=\
	$PLAN9/include/bio.h\

<$PLAN9/src/mksyslib

bcat: bcat.$O $PLAN9/lib/$LIB
	$LD -o bcat bcat.$O -lbio -lfmt -lutf

