PLAN9=../..
<$PLAN9/src/mkhdr

LIB=libbio.a

OFILES=\
	bbuffered.$O\
	bfildes.$O\
	bflush.$O\
	bgetc.$O\
	bgetd.$O\
	binit.$O\
	boffset.$O\
	bprint.$O\
	bputc.$O\
	brdline.$O\
	brdstr.$O\
	bread.$O\
	bseek.$O\
	bwrite.$O\
	bgetrune.$O\
	bputrune.$O\

HFILES=\
	$PLAN9/include/bio.h\

<$PLAN9/src/mksyslib

bcat: bcat.$O $LIB
	$CC -o bcat bcat.$O -L$PLAN9/lib -lbio -lfmt -lutf

