#!/bin/sh

PLAN9=`pwd` export PLAN9
PATH=$PLAN9/bin:$PATH export PATH

echo "Building mk..."
cd src
make
echo "Building everything..."
mk clean
echo "Installing everything..."
mk install
echo "Cleaning up..."
mk clean
echo "Renaming hard-coded paths to /usr/local/plan9..."
cd $PLAN9
sh lib/moveplan9.sh

echo " "
echo "Add these to your profile environment."
echo "	PLAN9=$PLAN9 export PLAN9"
echo '	PATH=$PATH:'"$PLAN9/bin export PATH"

