#!/bin/sh

PLAN9=`pwd` export PLAN9
PATH=$PLAN9/bin:$PATH export PATH

cd src
make
mk clean
mk install

echo "Set PLAN9=$PLAN9 in your profile environment."
echo 'Add $PLAN9/bin to your profile PATH.'

