<$PLAN9/src/mkhdr

TARG=aux/pm
OFILES=misc.$O\
	slug.$O\
	range.$O\
	queue.$O\
	page.$O\

HFILES=misc.h\

BIN=/$objtype/bin
<$PLAN9/src/mkone
CC=c++/$CC
LD=c++/$LD
CFLAGS=

slug.$O:	slug.h
range.$O:	range.h slug.h
queue.$O:	page.h range.h slug.h
page.$O:	page.h range.h slug.h

test:V:	$O.out
	tryout $O.out
