<$PLAN9/src/mkhdr

LIB=libmp.a
UNAME=`uname`
A=`[ $UNAME = Darwin ] && echo -Darwin`
OFILES=\
	mpdigdiv$A.$O\
	mpvecadd$A.$O\
	mpvecdigmuladd$A.$O\
	mpvecdigmulsub$A.$O\
	mpvecsub$A.$O\

HFILES=$PLAN9/include/mp.h ../port/dat.h

<$PLAN9/src/mksyslib
