<$PLAN9/src/mkhdr

TARG=devdraw

WSYSOFILES=\
	devdraw.$O\
	latin1.$O\
	mouseswap.$O\
	winsize.$O\

<|sh ./mkwsysrules.sh

OFILES=$WSYSOFILES

HFILES=\
	devdraw.h\

<$PLAN9/src/mkone

$O.drawclient: drawclient.$O drawfcall.$O
	$LD -o $target $prereq

$O.snarf: x11-alloc.$O x11-cload.$O x11-draw.$O x11-fill.$O x11-get.$O x11-init.$O x11-itrans.$O x11-keysym2ucs.$O x11-load.$O x11-pixelbits.$O x11-unload.$O x11-wsys.$O snarf.$O latin1.$O devdraw.$O
	$LD -o $target $prereq

$O.mklatinkbd: mklatinkbd.$O
	$LD -o $target $prereq

latin1.$O: latin1.h

latin1.h: $PLAN9/lib/keyboard $O.mklatinkbd
	./$O.mklatinkbd -r $PLAN9/lib/keyboard | sed 's/, }/ }/' >$target

CLEANFILES=latin1.h $O.mklatinkbd

# Still in progress: Cocoa/Objective C version of devdraw

%-objc.$O: %.m
	$CC $CFLAGS -o $target $stem.m

cocoa: devdraw.o latin1.o mouseswap.o winsize.o osx-draw.o cocoa-screen-objc.o cocoa-srv.o cocoa-thread.o
	$LD -o $target $prereq

devdraw-cocoa: devdraw.o latin1.o mouseswap.o winsize.o osx-screen-objc.o osx-draw.o osx-srv-objc.o osx-delegate-objc.o
	$LD -o $target $prereq

install-macargv: $O.macargv
	install $O.macargv $PLAN9/bin/macargv

$O.macargv: macargv.$O
	$LD -o $target $prereq

install: $MACARGV
install: mklatinkbd.install
