PLAN9=../../..
<$PLAN9/src/mkhdr

LIB=libsec.a

OFILES=\
	aes.$O\
	des.$O\
	desmodes.$O\
	fastrand.$O\
	genrandom.$O\
	md5.$O\
	md5block.$O\
	sha1.$O\
	sha1block.$O\

HFILES=$PLAN9/include/libsec.h

<$PLAN9/src/mksyslib

