<$PLAN9/src/mkhdr

TARG=factotum
PROTO=\
	apop.$O\
	chap.$O\
	p9any.$O\
	p9sk1.$O\
	rsa.$O\

OFILES=\
	$PROTO\
	attr.$O\
	confirm.$O\
	conv.$O\
	ctl.$O\
	dsa.$O\
	fs.$O\
	key.$O\
	log.$O\
	main.$O\
	plan9.$O\
	pkcs1.$O\
	proto.$O\
	rpc.$O\
	util.$O\
	xio.$O\
	secstore.$O\

HFILES=dat.h

<$PLAN9/src/mkone

$O.test: test.$O
	$LD -o $target $prereq

