.TH ABS 3
.SH NAME
abs, labs \- integer absolute values
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.B
int	abs(int a)
.PP
.B
long	labs(long a)
.SH DESCRIPTION
.I Abs
returns
the absolute value of integer
.IR a ,
and
.I labs
does the same for a long.
.SH SOURCE
.B /sys/src/libc/port/abs.c
.SH SEE ALSO
.IR floor (2)
for
.I fabs
.SH DIAGNOSTICS
.I Abs
and
.I labs
return
the most negative integer or long when the true result is unrepresentable.
