.TH CPUTIME 3
.SH NAME
cputime, times \- cpu time in this process and children
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.ta \w'\fLdouble 'u
.B
int	times(long t[4])
.PP
.B
double	cputime(void)
.SH DESCRIPTION
If
.I t
is non-null,
.I times
fills it in
with the number of milliseconds spent in user code, system calls,
child processes in user code, and child processes in system calls.
.I Cputime
returns the sum of those same times, converted to seconds.
.I Times
returns the elapsed real time, in milliseconds, that the process has been running.
.SH SOURCE
.B \*9/src/lib9/time.c
