.TH GETENV 3
.SH NAME
getenv, putenv \- access environment variables
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.nf
.B
char* getenv(char *name)
.br
.B
int   putenv(char *name, char *val)
.fi
.SH DESCRIPTION
.I Getenv
reads the contents of
.BI /env/ name
(see
.IR env (3))
into memory allocated with
.IR malloc (3),
0-terminates it,
and returns a pointer to that area.
If no file exists, 0
is returned.
.PP
.I Putenv
creates the file
.BI /env/ name
and writes the string
.I val
to it.  The terminating
.B 0
is not written.
If the file value cannot be written, \-1 is returned.
.SH SOURCE
.B /usr/local/plan9/src/libc/9sys
.SH SEE ALSO
.IR env (3)
.SH DIAGNOSTICS
Sets
.IR errstr .
