.TH HYPOT 3
.SH NAME
hypot \- Euclidean distance
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.nf
.B
double hypot(double x, double y)
.fi
.SH DESCRIPTION
.I Hypot
returns
.EX
	sqrt(x*x + y*y)
.EE
taking precautions against unwarranted overflows.
.SH SOURCE
.B /usr/local/plan9/src/libc/port/hypot.c
