.TH POSTNOTE 3
.SH NAME
postnote \- send a note to a process or process group
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.nf
.B
int	postnote(int who, int pid, char *note)
.fi
.SH DESCRIPTION
.I Postnote
sends a note to a process or process group.
If
.I who
is
.BR PNPROC ,
then
.I note
is sent to the process with id
.IR pid .
If
.I who
is
.BI PNGROUP , 
the note is delivered to the
process group containing the process with id
.IR pid .
For
.B PNGROUP
only, if the calling process is in the target group, the note is
.I not
delivered to that process.
.PP
Returns zero if the write succeeds, otherwise \-1.
.SH SOURCE
.B \*9/src/lib9/postnote.c
.SH "SEE ALSO"
.MR notify (3) ,
.MR intro (3)
.SH DIAGNOSTICS
Sets
.IR errstr .
