.TH POST9PSERVICE 3
.SH NAME
post9pservice \- post 9P service for use by clients
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.B
int post9pservice(int fd, char *name, char *mtpt)
.SH DESCRIPTION
.I Post9pservice
invokes
.MR 9pserve (4)
to post a new 9P service in the current 
``name space''
(see
.MR intro (4) )
named
.IR name .
Clients connecting to the posted service
are multiplexed onto a single 9P conversation with the server
on file descriptor
.IR fd .
.PP
If
.I mtpt
is non-nil,
.I post9pservice
mounts the service on
.IR mtpt ,
using
.MR 9pfuse (4) .
.SH "SEE ALSO
.MR intro (4) ,
.MR 9pfuse (4) ,
.MR 9pserve (4)
.SH SOURCE
.B \*9/src/lib9/post9p.c
