.TH TIME 3
.SH NAME
time, nsec \- time in seconds and nanoseconds since epoch
.SH SYNOPSIS
.B #include <u.h>
.br
.B #include <libc.h>
.PP
.nf
.B
long time(long *tp)
.PP
.B
vlong nsec(void)
.SH DESCRIPTION
Both
.I time
and
.I nsec
return the time since the epoch 00:00:00 GMT, Jan. 1, 1970.
The return value of the former is in seconds and the latter in nanoseconds.
For
.IR time ,
if
.I tp
is not zero then
.BI * tp
is also set to the answer.
.SH SOURCE
.B \*9/src/lib9/time.c
.SH DIAGNOSTICS
These functions set
.IR errstr .
.SH BUGS
To avoid name conflicts with the underlying system,
.I time
and
.I nsec
are preprocessor macros defined as
.I p9time
and
.IR p9nsec ;
see
.MR intro (3) .
