.TH VENTI 3
.SH NAME
venti \- archival storage server
.SH SYNOPSIS
.PP
.ft L
#include <u.h>
.br
#include <libc.h>
.br
#include <venti.h>
.SH DESCRIPTION
The Venti library provides support for writing Venti servers and clients.
This manual page describes general utility functions.
.PP
Other manual pages describe the library functions in detail.
.PP
.IM Venti-cache (3)
describes a simple in-memory block cache to help clients.
.PP
.IM Venti-conn (3)
describes routines for manipulating network connections
between Venti clients and servers.
.IM Venti-client (3)
and
.IM venti-server (3)
describe routines for writing clients
and servers on top of these.
.PP
.IM Venti-fcall (3)
describes the C representation of Venti protocol messages
and data structures.
It also describes routines that convert between the C representation
and the network and disk representations.
.PP
.IM Venti-file (3)
describes routines for writing clients that manipulate
Venti file trees
(see
.IM venti (7) ).
.PP
.IM Venti-log (3)
describes routines to access in-memory log buffers
as well as the logging that is done automatically by
the library.
.PP
.IM Venti-mem (3)
describes wrappers around the canonical
.IM malloc (3)
routines that abort on error.
.PP
.IM Venti-packet (3)
describes routines for 
manipulating zero-copy chains of
data buffers.
.PP
.IM Venti-zero (3)
describes routines to zero truncate and zero extend blocks
(see
.IM venti (7) ).
.SH SOURCE
.B \*9/src/libventi
.SH SEE ALSO
.IM venti (1) ,
.IM venti-cache (3) ,
.IM venti-client (3) ,
.IM venti-fcall (3) ,
.IM venti-file (3)
.IM venti-log (3) ,
.IM venti-mem (3) ,
.IM venti-packet (3) ,
.IM venti-server (3) ,
.IM venti-zero (3) ,
.IM venti (7) ,
.IM venti (8)
