<$PLAN9/src/mkhdr

BIN=$PLAN9/bin
#CFLAGS=-Fw
HFILES =\
	SConn.h\
	secstore.h\

OFILES =\
	pak.$O\
	password.$O\
	SConn.$O\
	util.$O\


TARG=aescbc secstore

<$PLAN9/src/mkmany

$O.aescbc:	aescbc.$O util.$O  $LIB ${SHORTLIB:%=$LIBDIR/lib%.a}
	$LD -o $target $prereq $LDFLAGS

