9SRC=..
include $(9SRC)/Makehdr

LIB=libframe.a

OFILES=\
	frbox.$O\
	frdelete.$O\
	frdraw.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frstr.$O\
	frutil.$O\

HFILES=\
	$(9SRC)/include/frame.h\
	$(9SRC)/include/draw.h\

include $(9SRC)/Makesyslib

