LIB=libframe.a
VERSION=2.0
PORTPLACE=devel/libframe
NAME=libdraw

OFILES=\
	frbox.$O\
	frdelete.$O\
	frdraw.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frstr.$O\
	frutil.$O\

all: $(LIB)

install: $(LIB)
	install -c -m 0644 $(LIB) $(PREFIX)/lib/$(LIB)
	install -c -m 0644 frame.h $(PREFIX)/include/frame.h
