<$PLAN9/src/mkhdr

LIB=libframe.a

OFILES=\
	frbox.$O\
	frdelete.$O\
	frdraw.$O\
	frinit.$O\
	frinsert.$O\
	frptofchar.$O\
	frselect.$O\
	frstr.$O\
	frutil.$O\

HFILES=\
	$PLAN9/include/frame.h\
	$PLAN9/include/draw.h\

<$PLAN9/src/mksyslib

