<$PLAN9/src/mkhdr
#
#		programs
#
TARG=\
	asn12dsa\
	asn12rsa\
	dsagen\
	dsasign\
	dsa2pub\
	dsa2ssh\
	passwd\
	pemdecode\
	pemencode\
	rsagen\
	rsafill\
	rsa2csr\
	rsa2pub\
	rsa2ssh\
	rsa2x509\
	ssh-agent\

DIRS=\
	factotum\
	secstore\

HFILES=$PLAN9/include/auth.h $PLAN9/include/authsrv.h

<$PLAN9/src/mkmany
<$PLAN9/src/mkdirs

RSA2=\
	rsa2ssh\
	rsafill\
	rsa2x509\
	rsa2pub\
	rsa2csr\
	dsa2ssh\
	dsa2pub\
	
${RSA2:%=$O.%}: rsa2any.$O
${RSA2:%=%.$O}: rsa2any.h
