<$PLAN9/src/mkhdr

TARG=emph_test
OFILES=emph_test.$O ../emphranges.$O

<$PLAN9/src/mkone

GTARG=g_test
GOFILES=g_test.$O ../regx.$O

$O.$GTARG:	$GOFILES
	$LD -o $target $prereq $LDFLAGS

test:V:	$O.emph_test $O.$GTARG
	./$O.emph_test
	./$O.$GTARG
	rc ./test_ctl.rc

clean:V:
	rm -f $O.emph_test $O.$GTARG *.o
