<$PLAN9/src/mkhdr

TARG=emph_test
# Stage 0: only emphranges is exercised; G1-G4 (rxexecute integration)
# are skipped. Stage 5 will need ../regx.$O ../buff.$O ../disk.$O
# ../util.$O plus mocks for the global `disk` and `textreadc` symbols.
OFILES=emph_test.$O ../emphranges.$O

<$PLAN9/src/mkone

test:V:	$O.emph_test
	./$O.emph_test
	rc ./test_ctl.rc
