.TH MNTGEN 4
.SH NAME
mntgen  \-  automatically generate mount points for file systems
.SH SYNOPSIS
.B mntgen
[
.B -s
.I service
]
[
.I mnt
]
.SH DESCRIPTION
.I Mntgen
mounts itself on
.I mnt
(default
.BR /n )
after the current contents,
creating subdirectories on demand as they are accessed.
It is intended to supply mount points automatically.
.PP
The
.B -s
option causes
.I mntgen
to post a 9P
.I service \fR
file.
.SH SOURCE
.B \*9/src/cmd/mntgen.c

