<$PLAN9/src/mkhdr

TARG=scat
OFILES=scat.$O\
	bitinput.$O\
	desc.$O\
	display.$O\
	dssread.$O\
	header.$O\
	hinv.$O\
	image.$O\
	patch.$O\
	plot.$O\
	posn.$O\
	prose.$O\
	qtree.$O\
	util.$O\

HFILES=sky.h
CFLAGS=$CFLAGS -I../map

LIB=../map/libmap/libmap.a
<$PLAN9/src/mkone

scat.$O:	strings.c

$LIB:V:
	cd ../map/libmap; mk

