TARG=samterm
OFILES=\
	main.$O\
	icons.$O\
	menu.$O\
	mesg.$O\
	rasp.$O\
	scroll.$O\
	flayer.$O\
	io.$O\
	plan9.$O\

HFILES=\
	samterm.h\
	flayer.h\
	$(PREFIX)/include/frame.h\

all: $(TARG)

install:
	install -c -m 0755 samterm $(PREFIX)/bin/samterm

