PLAN9=../../..
<$PLAN9/src/mkhdr

TARG=samterm
OFILES=\
	main.$O\
	icons.$O\
	menu.$O\
	mesg.$O\
	rasp.$O\
	scroll.$O\
	flayer.$O\
	io.$O\
	plan9.$O\

HFILES=\
	samterm.h\
	flayer.h\
	../sam/sam.h\
	../sam/mesg.h\
	$PLAN9/include/frame.h\
	$PLAN9/include/draw.h\

CFLAGS=$CFLAGS -I../sam
LDFLAGS=$LDFLAGS -lframe -ldraw -lthread -l9 -lregexp9 \
	-lbio -lfmt -lutf -L$X11/lib -lX11 -lm

o.samterm: $PLAN9/lib/libframe.a $PLAN9/lib/libdraw.a $PLAN9/lib/libthread.a

<$PLAN9/src/mkone
