<$PLAN9/src/mkhdr

TARG=samterm
OFILES=\
	main.$O\
	icons.$O\
	menu.$O\
	mesg.$O\
	rasp.$O\
	scroll.$O\
	flayer.$O\
	io.$O\
	plan9.$O\

HFILES=\
	samterm.h\
	flayer.h\
	../sam/sam.h\
	../sam/mesg.h\
	$PLAN9/include/frame.h\
	$PLAN9/include/draw.h\

CFLAGS=$CFLAGS -I../sam

<$PLAN9/src/mkone
