<$PLAN9/src/mkhdr

LIB=libauthsrv.a
OFILES=\
	_asgetticket.$O\
	_asrdresp.$O\
	authdial.$O\
	convA2M.$O\
	convM2A.$O\
	convM2PR.$O\
	convM2T.$O\
	convM2TR.$O\
	convPR2M.$O\
	convT2M.$O\
	convTR2M.$O\
	nvcsum.$O\
	opasstokey.$O\
	passtokey.$O\
	readnvram.$O\

HFILES=\
	$PLAN9/include/authsrv.h\

<$PLAN9/src/mksyslib
