<$PLAN9/src/mkhdr

TARG = qer\
	runq\

OFILES=

HFILES=../common/common.h\
	../common/sys.h\

LIB=../common/libcommon.a\

BIN=$PLAN9/bin/upas

UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\
	${TARG:%=%.c}\

<$PLAN9/src/mkmany
CFLAGS=$CFLAGS -I../common
