PLAN9=../..
<$PLAN9/src/mkhdr

LIB=libip.a
OFILES=\
	eipfmt.$O\
	parseip.$O\
	parseether.$O\
	myetheraddr.$O\
	myipaddr.$O\
	classmask.$O\
	bo.$O\
	readipifc.$O\
	ipaux.$O\
	ptclbsum.$O\

HFILES=\
	ip.h

<$PLAN9/src/mksyslib
