<$PLAN9/src/mkhdr

LIB=libip.a
OFILES=\
	bo.$O\
	classmask.$O\
	eipfmt.$O\
	freeipifc.$O\
	ipaux.$O\
	myipaddr.$O\
	parseether.$O\
	parseip.$O\
	ptclbsum.$O\
	udp.$O\
	$SYSNAME.$O\

HFILES=\
	ip.h

<$PLAN9/src/mksyslib

testreadipifc: testreadipifc.o $LIBDIR/$LIB
	$LD -o testreadipifc testreadipifc.o


