<$PLAN9/src/mkhdr

<../config

LIB=libcom.a
OFILES=bbox.$O\
	glob.$O\
	misc.$O\
	request.$O\
	rune.$O\
	tempnam.$O\
	getopt.$O\

HFILES=comments.h\
	gen.h\
	ext.h\
	request.h\
	path.h\
	rune.h\

<$PLAN9/src/mklib

CFLAGS=-c -D$SYSTEM 
