<$PLAN9/src/mkhdr

TARG=vf unvf

OFILES=

LIB=../common/libcommon.a\

HFILES=../common/common.h\
	 ../common/sys.h\


BIN=$PLAN9/bin/upas
UPDATE=\
	mkfile\
	$HFILES\
	${OFILES:%.$O=%.c}\

<$PLAN9/src/mkmany
CFLAGS=$CFLAGS -I../common
