<$PLAN9/src/mkhdr

TARG=auxstats

OFILES=\
	$SYSNAME.$O\
	main.$O\

HFILES=\
	dat.h\

SHORTLIB=bio 9

<$PLAN9/src/mkone

KVM=`{if uname |grep BSD >/dev/null; then echo -lkvm; fi}
LDFLAGS=$LDFLAGS $KVM

