<$PLAN9/src/mkhdr

TARG=	fs\

OFILES=\
	fs.$O\
	imap4.$O\
	mbox.$O\
	plan9.$O\
	pop3.$O\
	strtotm.$O\

LIB=../common/libcommon.a\
#	/usr/local/plan9/lib/libthread.a

HFILES= ../common/common.h\
	dat.h

BIN=$PLAN9/bin/upas

UPDATE=\
	mkfile\
	$HFILES\
	${TARG:%=%.c}\
	${OFILES:%.$O=%.c}\

<$PLAN9/src/mkone
CFLAGS=$CFLAGS  -I../common
# CFLAGS=$CFLAGS -I/sys/include -I../common
