.TH COLORS 1
.SH NAME
colors, cmapcube \- display color map
.SH SYNOPSIS
.PP
.B colors
[
.B -r
.B -x
]
.PP
.B cmapcube
[
.B -nbw
]
.SH DESCRIPTION
.I Colors
presents a grid showing the colors in the RGBV color map
(see
.MR color (7) ).
.PP
Clicking mouse button 1 over a color in the grid will display the map index for that color,
its
red, green, and blue components,
and the 32-bit hexadecimal color value as defined in
.MR allocimage (3) .
If the
.B -x
option is specified, the components will also be listed in hexadecimal.
.PP
The
.B -r
option instead shows, in the same form, a grey-scale ramp.
.PP
A menu on mouse button 3 contains a single entry, to exit the program.
.PP
.I Cmapcube
presents the same colors but in a 3-dimensional cube.
Dragging with button 1 rotates the cube.
Clicking on a color with button 2
displays the map index for that color.
Clicking button 3 exits.
.PP
The
.B -n
option disables drawing of the color squares.
The
.B -b
and
.B -w
options set the background (default grey)
to black or white.
.SH SOURCE
.B \*9/src/cmd/draw/colors.c
.SH SEE ALSO
.MR color (7)
