.TH DEVDRAW 1
.SH NAME
devdraw \- draw device simulator
.SH SYNOPSIS
invoked via 
.I initdraw
(see
.MR graphics (3) )
.SH DESCRIPTION
.I Devdraw
serves a custom graphics protocol and is the only program
that talks directly to X window servers.
On Macintosh, setting
.BI devdrawretina
to
.BI 1
will cause
.I devdraw
to use all available physical pixels on a retina display.
.SH SOURCE
.B \*9/src/cmd/devdraw
.SH "SEE ALSO
.MR draw (3) ,
.MR drawfcall (3) ,
.MR graphics (3)
.SH BUGS
.I Devdraw
should probably present a standard 9P server
instead of using its own protocol.
