.TH DOCTYPE 1 
.SH NAME
doctype \- intuit command line for formatting a document
.SH SYNOPSIS
.B doctype
[
.B -n
]
[
.B -T
.I dev
]
[
.I file
]
\&...
.SH DESCRIPTION
.I Doctype
examines a
.MR troff (1)
input file to deduce the appropriate text formatting command
and prints it on standard output.
.I Doctype
recognizes input for
.MR troff (1) ,
related preprocessors like
.MR eqn (1) ,
and the 
.MR ms (7)
and
.I mm 
macro packages.
.PP
Option
.B -n
invokes
.I nroff
instead of
.IR troff .
The
.B -T
option is passed to
.IR troff .
.SH EXAMPLES
.TP
.L
eval `{doctype chapter.?} | lp 
Typeset files named
.BR chapter.0 ,
.BR chapter.1 ,
\&...
.SH SOURCE
.B \*9/bin/doctype
.SH SEE ALSO
.IR troff (1), 
.IR eqn (1), 
.IR tbl (1), 
.IR pic (1), 
.MR grap (1) ,
.MR ms (7) ,
.MR man (7)
.SH BUGS
In true A.I. style, its best guesses are inspired rather than accurate.
