.TH FORTUNE 1
.SH NAME
fortune \- sample lines from a file
.SH SYNOPSIS
.B fortune
[
.I file
]
.SH DESCRIPTION
.I Fortune
prints a one-line aphorism chosen at random.
If a
.I file
is specified, the saying is taken from that file;
otherwise it is selected from
.BR \*9/lib/fortunes .
.SH FILES
.B \*9/lib/fortunes
.br
.B \*9/lib/fortunes.index
\ \ fast lookup table, maintained automatically
.SH SOURCE
.B \*9/src/cmd/fortune.c
