.TH MKDIR 1
.SH NAME
mkdir \- make a directory
.SH SYNOPSIS
.B mkdir
[
.B -p
] [
.B -m
. I mode
]
.I dirname ...
.SH DESCRIPTION
.I Mkdir
creates the specified directories.
It
requires write permission in the parent directory.
.PP
If the
.B -p
flag is given,
.I mkdir
creates any necessary parent directories
and does not complain if the target directory already exists.
.PP
The
.B -m
flag sets the permissions to be used when creating the directory.
The default is 0777.
.SH "SEE ALSO"
.MR rm (1)
.br
.IR cd
in
.MR rc (1)
.SH SOURCE
.B \*9/src/cmd/mkdir.c
.SH DIAGNOSTICS
.I Mkdir
returns null exit status if all directories were successfully made.
Otherwise it prints a diagnostic and returns
.B \&"error"
status.
