.TH NETKEY 1
.SH NAME
netkey \- challenge-response authentication
.SH SYNOPSIS
.PP
.B netkey
.SH DESCRIPTION
.PP
.I Netkey
prompts for a password to encrypt network challenges.
It is a substitute for a SecureNet box.
.SH SOURCE
.B \*9/src/cmd/netkey.c
.SH "SEE ALSO"
.IR encrypt (3)
.PP
Robert Morris and Ken Thompson,
``UNIX Password Security,''
.I AT&T Bell Laboratories Technical Journal
Vol 63 (1984), pp. 1649-1672
