.TH SFTPCACHE 1
.SH NAME
sftpcache \- cache sftp connections
.SH SYNOPSIS
.B sftpcache
.I system
.SH DESCRIPTION
.I Sftpcache
multiplexes clients onto persistent 
.MR sftp (1)
connections.
It runs
.I sftp
.I system 
and posts a socket named
.IB system .sftp
in the name space directory
(see
.MR intro (4) ).
Clients can connect to the socket, one at a time,
to interact with the
.I sftp
session.
.PP
.I Sftpcache
is used by
.MR netfiles (1) .
.SH SOURCE
.B \*9/src/cmd/sftpcache.c
.SH SEE ALSO
.MR ssh (1) ,
.MR sftp (1) ,
.MR netfiles (1)
.SH BUGS
.I Sftpcache
only works with OpenSSH versions 4.3 and earlier;
later versions do not print the
.B sftp>
prompt frequently enough.
