.TH SLEEP 1
.SH NAME
sleep \- suspend execution for an interval
.SH SYNOPSIS
.B sleep
.I time
.SH DESCRIPTION
.I Sleep
suspends execution for
.I time
seconds.
.SH EXAMPLES
Execute a command
100 seconds hence.
.IP
.EX
{sleep 100; command}&
.EE
.PP
Repeat a command every 30 seconds.
.IP
.EX
while (){
	command
	sleep 30
}
.EE
.SH SOURCE
.B \*9/src/cmd/sleep.c
.SH "SEE ALSO"
.MR sleep (3)
