.TH SOELIM 1
.\" .so in the NAME line confuses the ptx machinery; sorry
.SH NAME
soelim \- preprocess so inclusion commands in troff input 
.SH SYNOPSIS
.B soelim
[
.I files ...
]
.SH DESCRIPTION
.I Soelim
reads the specified files or the standard input and performs
the textual inclusion implied by
.MR troff (1)
directives of the form
.TP
.B "\&.so some_file
.PP
when they appear at the beginning of input lines.  This is useful when
using programs such as
.MR tbl (1)
that do not normally do this, allowing
placement of individual tables or other text objects in separate files
to be run as a part of a large document.
.SH SOURCE
.B \*9/bin/soelim
.SH "SEE ALSO"
.MR deroff (1) ,
.MR troff (1)
