.TH SPELL 1
.SH NAME
spell, sprog \- find spelling errors
.SH SYNOPSIS
.B spell
[
.I options
]
\&...
[
.I file
]
\&...
.PP
.B sprog
[
.I options
]
[
.B -f
.I file
]
.SH DESCRIPTION
.I Spell
looks up words from the named
.I files
(standard input default)
in a spelling list and places
possible misspellings\(emwords 
not sanctioned there\(emon the standard output.
.PP
.I Spell
ignores constructs of
.MR troff (1)
and its standard preprocessors.
It understands these options:
.TP
.B -b
Check British spelling.
.TP
.B -v
Print all words not literally in the spelling list, with
derivations.
.TP
.B -x
Print, marked with
.LR = ,
every stem as it is looked up in the spelling list,
along with its affix classes.
.PP
As a matter of policy, 
.I spell
does not admit multiple spellings of the same word.
Variants that follow general rules are preferred
over those that don't, even when the unruly spelling is
more common.
Thus, in American usage, `modelled', `sizeable', and `judgment' are
rejected in favor of `modeled', `sizable', and `judgement'.
Agglutinated variants are shunned: `crewmember' and `backyard'
cede to `crew member' and  `back yard' (noun) or `back-yard' 
(adjective).
.SH FILES
.TP
.B \*9/lib/amspell
American spelling list
.TP
.B \*9/lib/brspell
British spelling list
.TP
.B \*9/bin/sprog
The actual spelling checker.
It expects one word per line on standard input,
and takes the same arguments as
.IR spell .
.SH SOURCE
.TF \*9/src/cmd/spell
.TP
.B \*9/bin/spell
the script
.TP
.B \*9/src/cmd/spell
source for
.I sprog
.SH SEE ALSO
.MR deroff (1)
.SH BUGS
The heuristics of
.MR deroff (1)
used to excise formatting information are imperfect.
.PP
The spelling list's coverage is uneven;
in particular biology, medicine, and chemistry, and
perforce proper names,
not to mention languages other than English,
are covered very lightly.
