.TH TOUCH 1
.SH NAME
touch \- set modification date of a file
.SH SYNOPSIS
.B touch
[
.B -c
]
[
.B -t
.I time
]
.I file ...
.SH DESCRIPTION
.I Touch
attempts to set the modification time of the
.I files
to 
.I time
(by default, the current time).
If a
.I file
does not exist,
it will be created unless option
.B -c
is present.
.SH SOURCE
.B \*9/src/cmd/touch.c
.SH SEE ALSO
.MR ls (1) ,
.MR stat (3) ,
.MR chmod (1)
.SH BUGS
.I Touch
will not touch directories.
