<$PLAN9/src/mkhdr
<|osxvers
<|sh ../devdraw/mkwsysrules.sh
<|sh freetyperules.sh $WSYSTYPE $X11H

TARG=fontsrv

HFILES=a.h

OFILES=\
	main.$O\
	pjw.$O\
	$WSYSTYPE.$O\

<$PLAN9/src/mkone

showpjw: showpjw.c
	9c showpjw.c
	9l -o showpjw showpjw.o
