<$PLAN9/src/mkhdr

TARG=9term win

OFILES=\
	rcstart.$O\
	$SYSNAME.$O\

SHORTLIB=complete frame draw plumb fs mux thread 9

<$PLAN9/src/mkmany

LDFLAGS=-L$X11/lib -lX11

Linux.$O FreeBSD.$O: bsdpty.c

