<$PLAN9/src/mkhdr

TARG=9term win

OFILES=\
	rcstart.$O\
	$SYSNAME.$O\

HFILES=dat.h fns.h term.h

<$PLAN9/src/mkmany

Darwin.$O Linux.$O FreeBSD.$O DragonFly.$O: bsdpty.c

$O.9term: data.$O scrl.$O time.$O util.$O wind.$O

