<$PLAN9/src/mkhdr

TARG=dump9660 mk9660

OFILES=

DFILES=\
	boot.$O\
	cdrdwr.$O\
	conform.$O\
	direc.$O\
	dump.$O\
	dump9660.$O\
	ichar.$O\
	jchar.$O\
	path.$O\
	unix.$O\
	rune.$O\
	sysuse.$O\
	util.$O\
	write.$O\

HFILES=iso9660.h

<$PLAN9/src/mkmany

$O.dump9660: $DFILES

mk9660.$O:V:
	# nothing

$O.mk9660: mk9660.sh
	cp mk9660.sh $target
